insert into point_reward (member_id, pay_at, point)
values ('member_1', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_2', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_3', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_4', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_5', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_16', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_27', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_18', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_39', TIMESTAMPADD(DAY, -11, NOW()), 100),
       ('member_40', TIMESTAMPADD(DAY, -11, NOW()), 100),

       ('member_1', TIMESTAMPADD(DAY, -10, NOW()), 200),
       ('member_2', TIMESTAMPADD(DAY, -10, NOW()), 200),
       ('member_3', TIMESTAMPADD(DAY, -10, NOW()), 200),
       ('member_4', TIMESTAMPADD(DAY, -10, NOW()), 200),
       ('member_5', TIMESTAMPADD(DAY, -10, NOW()), 200),
       ('member_6', TIMESTAMPADD(DAY, -10, NOW()), 100),
       ('member_7', TIMESTAMPADD(DAY, -10, NOW()), 100),
       ('member_8', TIMESTAMPADD(DAY, -10, NOW()), 100),
       ('member_9', TIMESTAMPADD(DAY, -10, NOW()), 100),
       ('member_10', TIMESTAMPADD(DAY, -10, NOW()), 100),

       ('member_1', TIMESTAMPADD(DAY, -9, NOW()), 300),
       ('member_12', TIMESTAMPADD(DAY, -9, NOW()), 100),
       ('member_3', TIMESTAMPADD(DAY, -9, NOW()), 300),
       ('member_4', TIMESTAMPADD(DAY, -9, NOW()), 300),
       ('member_5', TIMESTAMPADD(DAY, -9, NOW()), 300),
       ('member_26', TIMESTAMPADD(DAY, -9, NOW()), 100),
       ('member_17', TIMESTAMPADD(DAY, -9, NOW()), 100),
       ('member_18', TIMESTAMPADD(DAY, -9, NOW()), 100),
       ('member_19', TIMESTAMPADD(DAY, -9, NOW()), 100),
       ('member_10', TIMESTAMPADD(DAY, -9, NOW()), 200),

       ('member_1', TIMESTAMPADD(DAY, -8, NOW()), 400),
       ('member_2', TIMESTAMPADD(DAY, -8, NOW()), 100),
       ('member_3', TIMESTAMPADD(DAY, -8, NOW()), 400),
       ('member_4', TIMESTAMPADD(DAY, -8, NOW()), 400),
       ('member_5', TIMESTAMPADD(DAY, -8, NOW()), 400),
       ('member_6', TIMESTAMPADD(DAY, -8, NOW()), 100),
       ('member_7', TIMESTAMPADD(DAY, -8, NOW()), 100),
       ('member_8', TIMESTAMPADD(DAY, -8, NOW()), 100),
       ('member_9', TIMESTAMPADD(DAY, -8, NOW()), 100),
       ('member_10', TIMESTAMPADD(DAY, -8, NOW()), 300),

       ('member_1', TIMESTAMPADD(DAY, -7, NOW()), 500),
       ('member_2', TIMESTAMPADD(DAY, -7, NOW()), 200),
       ('member_3', TIMESTAMPADD(DAY, -7, NOW()), 500),
       ('member_4', TIMESTAMPADD(DAY, -7, NOW()), 500),
       ('member_15', TIMESTAMPADD(DAY, -7, NOW()), 100),
       ('member_6', TIMESTAMPADD(DAY, -7, NOW()), 200),
       ('member_7', TIMESTAMPADD(DAY, -7, NOW()), 200),
       ('member_8', TIMESTAMPADD(DAY, -7, NOW()), 200),
       ('member_9', TIMESTAMPADD(DAY, -7, NOW()), 200),
       ('member_10', TIMESTAMPADD(DAY, -7, NOW()), 400),

       ('member_1', TIMESTAMPADD(DAY, -6, NOW()), 600),
       ('member_2', TIMESTAMPADD(DAY, -6, NOW()), 300),
       ('member_3', TIMESTAMPADD(DAY, -6, NOW()), 600),
       ('member_4', TIMESTAMPADD(DAY, -6, NOW()), 600),
       ('member_15', TIMESTAMPADD(DAY, -6, NOW()), 200),
       ('member_6', TIMESTAMPADD(DAY, -6, NOW()), 300),
       ('member_7', TIMESTAMPADD(DAY, -6, NOW()), 300),
       ('member_8', TIMESTAMPADD(DAY, -6, NOW()), 300),
       ('member_9', TIMESTAMPADD(DAY, -6, NOW()), 300),
       ('member_10', TIMESTAMPADD(DAY, -6, NOW()), 500),

       ('member_1', TIMESTAMPADD(DAY, -5, NOW()), 700),
       ('member_2', TIMESTAMPADD(DAY, -5, NOW()), 400),
       ('member_3', TIMESTAMPADD(DAY, -5, NOW()), 700),
       ('member_4', TIMESTAMPADD(DAY, -5, NOW()), 700),
       ('member_15', TIMESTAMPADD(DAY, -5, NOW()), 300),
       ('member_6', TIMESTAMPADD(DAY, -5, NOW()), 400),
       ('member_17', TIMESTAMPADD(DAY, -5, NOW()), 100),
       ('member_8', TIMESTAMPADD(DAY, -5, NOW()), 400),
       ('member_9', TIMESTAMPADD(DAY, -5, NOW()), 400),
       ('member_10', TIMESTAMPADD(DAY, -5, NOW()), 600),

       ('member_1', TIMESTAMPADD(DAY, -4, NOW()), 800),
       ('member_2', TIMESTAMPADD(DAY, -4, NOW()), 500),
       ('member_13', TIMESTAMPADD(DAY, -4, NOW()), 100),
       ('member_4', TIMESTAMPADD(DAY, -4, NOW()), 800),
       ('member_15', TIMESTAMPADD(DAY, -4, NOW()), 400),
       ('member_6', TIMESTAMPADD(DAY, -4, NOW()), 500),
       ('member_7', TIMESTAMPADD(DAY, -4, NOW()), 100),
       ('member_18', TIMESTAMPADD(DAY, -4, NOW()), 100),
       ('member_19', TIMESTAMPADD(DAY, -4, NOW()), 100),
       ('member_10', TIMESTAMPADD(DAY, -4, NOW()), 700),

       ('member_1', TIMESTAMPADD(DAY, -3, NOW()), 900),
       ('member_2', TIMESTAMPADD(DAY, -3, NOW()), 600),
       ('member_3', TIMESTAMPADD(DAY, -3, NOW()), 100),
       ('member_4', TIMESTAMPADD(DAY, -3, NOW()), 900),
       ('member_15', TIMESTAMPADD(DAY, -3, NOW()), 500),
       ('member_6', TIMESTAMPADD(DAY, -3, NOW()), 600),
       ('member_7', TIMESTAMPADD(DAY, -3, NOW()), 200),
       ('member_8', TIMESTAMPADD(DAY, -3, NOW()), 100),
       ('member_9', TIMESTAMPADD(DAY, -3, NOW()), 100),
       ('member_10', TIMESTAMPADD(DAY, -3, NOW()), 800),

       ('member_1', TIMESTAMPADD(DAY, -2, NOW()), 1000),
       ('member_2', TIMESTAMPADD(DAY, -2, NOW()), 700),
       ('member_3', TIMESTAMPADD(DAY, -2, NOW()), 200),
       ('member_4', TIMESTAMPADD(DAY, -2, NOW()), 1000),
       ('member_15', TIMESTAMPADD(DAY, -2, NOW()), 600),
       ('member_6', TIMESTAMPADD(DAY, -2, NOW()), 700),
       ('member_7', TIMESTAMPADD(DAY, -2, NOW()), 300),
       ('member_8', TIMESTAMPADD(DAY, -2, NOW()), 200),
       ('member_9', TIMESTAMPADD(DAY, -2, NOW()), 200),
       ('member_10', TIMESTAMPADD(DAY, -2, NOW()), 900),

       ('member_1', TIMESTAMPADD(DAY, -1, NOW()), 100),
       ('member_2', TIMESTAMPADD(DAY, -1, NOW()), 800),
       ('member_3', TIMESTAMPADD(DAY, -1, NOW()), 300),
       ('member_4', TIMESTAMPADD(DAY, -1, NOW()), 100),
       ('member_15', TIMESTAMPADD(DAY, -1, NOW()), 600),
       ('member_6', TIMESTAMPADD(DAY, -1, NOW()), 800),
       ('member_7', TIMESTAMPADD(DAY, -1, NOW()), 400),
       ('member_8', TIMESTAMPADD(DAY, -1, NOW()), 300),
       ('member_9', TIMESTAMPADD(DAY, -1, NOW()), 300),
       ('member_10', TIMESTAMPADD(DAY, -1, NOW()), 1000);

